version: 2
jobs:
  lint-test:
    working_directory: ~/app/
    docker:
      - image: cimg/node:12.21.0
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}
      - run: NODE_ENV=development yarn
      - run:
          nane: Lint Everything
          command: yarn lint
      - run:
          name: Tests
          command: yarn test --maxWorkers 2
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}
          paths:
            - ~/app/node_modules/
  
  build-test:
    working_directory: ~/app/
    docker:
      - image: cimg/node:12.21.0
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}
      - run: NODE_ENV=development yarn
      - run:
          nane: run test build
          command: ./run build
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}
          paths:
            - ~/app/node_modules/

  publish-uat:
    working_directory: ~/app/
    docker:
      - image: cimg/node:12.21.0
    resource_class: small
    environment:
      AWS_STAGE: uat
      AWS_DEFAULT_REGION: ap-southeast-2
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}
      - run:
          name: Install app dependancies
          command: NODE_ENV=development yarn install
      - run:
          nane: Build result to dist folder
          command: ./run build --stage uat
      - run:
          name: Deploy to UAT
          command: ./run deploy-uat
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}
          paths:
            - ~/app/node_modules/

  publish-prod:
    working_directory: ~/app/
    docker:
      - image: cimg/node:12.21.0
    resource_class: small
    environment:
      AWS_STAGE: prod
      AWS_DEFAULT_REGION: ap-southeast-2
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}
      - run:
          name: Install app dependancies
          command: NODE_ENV=development yarn install
      - run:
          nane: Build result to dist folder
          command: ./run build --stage prod
      - run:
          name: Deploy to PRODUCTION
          command: ./run deploy
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}
          paths:
            - ~/app/node_modules/

workflows:
  version: 2
  ci-workflow:
    jobs:
      - lint-test
      - build-test:
          requires:
            - lint-test
      - hold-publish-uat:
          type: approval
          requires:
            - build-test
          filters:
            branches:
              only:
                - develop
      - publish-uat:
          requires:
            - hold-publish-uat
      - hold-publish-prod:
          type: approval
          requires:
            - build-test
          filters:
            branches:
              only:
                - main
      - publish-prod:
          requires:
            - hold-publish-prod
