#!/bin/sh
# AWS Lambda helper script

APP_NAME=myapi
NET_NAME=bridge1
# specify name here to automatically start and stop database
DBAPP_NAME=pgdb

update_package_json() {
  echo "const fs = require('fs'), PKG='package.json', pkg = JSON.parse(fs.readFileSync(PKG, 'utf8'))
pkg.main = 'src/index.js'
pkg.engines = { node : '>=10.0.0' }
pkg.scripts = {
  compile: 'tsc',
  start: 'node ./dist/server.js',
  dev: 'webpack --watch',
  test: 'yarn jest',
  sq: 'sequelize-cli',
  'lint': 'eslint ./src ./database',
  'lint:fix': 'eslint --fix ./src ./database',
  'pretty': 'prettier -c ./src',
  'pretty:fix': 'prettier -w ./src'
}
fs.writeFileSync(PKG, JSON.stringify(pkg, null, 2));
" | node -
}


app_init() { 
  yarn init -y
  # add expressjs and graphql
  APPDEPS="ajv ajv-formats lodash moment-timezone chance graphql 
    express apollo-server-express sequelize pg jwt-simple axios
    apollo-server-lambda aws-lambda serverless-http"
  # aws-serverless-express

  yarn add $APPDEPS

  # Add webpack, babel transpiler, eslint, prettier and jest/supertest
  yarn add -D webpack webpack-cli webpack-node-externals raw-loader \
    typescript ts-loader @types/node @types/validator @types/express \
    eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin \
    prettier eslint-plugin-prettier eslint-config-prettier \
    jest ts-jest @types/jest supertest @types/supertest jest-transform-graphql \
    sequelize-cli @types/sequelize \
    serverless serverless-offline serverless-domain-manager serverless-webpack
  
  update_package_json
}


app_reset() {
  rm -rf ./node_modules ./dist
  rm package.json yarn.lock package-lock.json yarn-error.log
}


app_hook_link() {
  ln -s ../../hooks/pre-commit .git/hooks/pre-commit
}


auto_stop_db() {
  docker ps --format "{{.Names}}" | grep "$DBAPP_NAME" > /dev/null
  if [ $? = 0 ]; then ./db stop; fi
}


app_stop() {
  # stop database server
  echo "Use Ctrl+C to stop app"
  if [ ! "" = "$DBAPP_NAME" ]; then auto_stop_db; fi
}


auto_start_db() {
  docker ps --format "{{.Names}}" | grep "$DBAPP_NAME" > /dev/null
  if [ ! $? = 0 ]; then
    ./db start;
    echo ">> Database ($DBAPP_NAME) started"
  else
    echo ">> Database ($DBAPP_NAME) already running"
  fi
}


app_start() {
  # start database server
  if [ ! "" = "$DBAPP_NAME" ]; then
    auto_start_db;
    sleep 3
  fi

  # run node file
  yarn sls offline start --stage dev
}


app_build() {
  echo "Building"
  yarn sls package $*
}


app_test() {
  yarn jest --env=node --colors --coverage ./src
}


app_sequelize() {
  yarn sequelize $*
}


app_deploy_uat() {
  echo "Deploying to production"
  yarn sls config credentials --provider aws --profile profile-serverless --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
  yarn sls deploy --stage uat --package ./.serverless
}


app_deploy_prod() {
  echo "Deploying to production"
  yarn sls config credentials --provider aws --profile profile-serverless --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
  yarn sls deploy --stage prod --package ./.serverless
}

app_get_serverless_forceincludes(){
  echo "const fs = require('fs'), PKG='package.json', pkg = JSON.parse(fs.readFileSync(PKG, 'utf8'));
  const print=console.log;
  const packages=Object.keys(pkg.dependencies);
  const exclusions=['aws-lambda'];
  packages.forEach(item => {if (exclusions.indexOf(item) < 0) print('        - ' + item)})
  " | node -
}

app_debug() {
  DEPS=$(echo "const fs = require('fs'), PKG='package.json', pkg = JSON.parse(fs.readFileSync(PKG, 'utf8'));
  const print=console.log;
  const packages=Object.keys(pkg.dependencies);
  const exclusions=['aws-lambda'];
  packages.forEach(item => {if (exclusions.indexOf(item) < 0) print(item)})
" | node -)
echo $DEPS
}


# import environment variables for local testing
set -a; if [ -f '.env' ]; then . ./.env; fi; set +a

if [ "$1" = "init" ]; then app_init; exit; fi
if [ "$1" = "reset" ]; then app_reset; exit; fi
if [ "$1" = "hook" ]; then app_hook_link; exit; fi

if [ "$1" = "start" ]; then app_start; exit; fi
if [ "$1" = "stop" ]; then app_stop; exit; fi

if [ "$1" = "build" ]; then shift 1; app_build $*; exit; fi

if [ "$1" = "test" ]; then app_test; exit; fi
if [ "$1" = "lint" ]; then yarn lint; exit; fi

if [ "$1" = "deploy" ]; then app_deploy_prod; exit; fi
if [ "$1" = "deploy-uat" ]; then app_deploy_uat; exit; fi

if [ "$1" = "sq" ]; then shift 1; app_sequelize $*; exit; fi
if [ "$1" = "get-includes" ]; then app_get_serverless_forceincludes; exit; fi

if [ "$1" = "debug" ]; then app_debug; exit; fi

echo "Command not found"
