service: apollo-ts-api

frameworkVersion: '>=1.1.0 <=3.0.0'

# order of plugins is important serverless-plugin-typescript should come first
plugins:
  - serverless-webpack
  - serverless-offline
#  - serverless-domain-manager

provider:
  name: aws
  profile: profile-serverless
  runtime: nodejs12.x
  stage: ${opt:stage, 'prod'}
  region: us-east-1
  timeout: 30
  environment:
    DB_URL: ${self:custom.${self:custom.stage}.DB_URL}
    JWT_SECRET: 'jg89g895yt475t45t9fe'

functions:
  apts-graphql:
    handler: src/index.gqlhandler
    memorySize: 256
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
  # Comment out REST handler if not used
  # Separate handler file for REST handler improves startup time
  apts-rest:
    handler: src/index2.resthandler
    memorySize: 256
    events:
      - http: 'POST /rest'
      - http: 'POST /rest/{any+}'
      - http: 'GET /rest'
      - http: 'GET /rest/{any+}'

custom:
  stage: ${opt:stage, 'prod'}
  defaultConfigType: 'cloud'
  # The force includes list can be generated with the command ./run get-includes
  webpack:
    includeModules:
      forceInclude:
        - ajv
        - ajv-formats
        - apollo-server-express
        - apollo-server-lambda
        - axios
        - chance
        - express
        - graphql
        - jwt-simple
        - lodash
        - moment-timezone
        - pg
        - sequelize
        - serverless-http
    packager: 'yarn'
  serverless-offline:
    port: 4000
    host: '0.0.0.0'
  # customDomain:
  #   domainName: ${self:custom.${self:custom.stage}.API_DOMAIN}
  #   basePath: ''
  #   certificateName: 'rokt.dev'
  #   stage: ${self:provider.stage}
  #   createRoute53Record: true

  # stage specific variables
  dev:
    DB_URL: ${env:DB_URL}
    API_DOMAIN: local-api.test.rokt.dev

  uat:
    DB_URL: ${env:UAT_DB_URL}
    API_DOMAIN: uat-api.test.rokt.dev

  prod:
    DB_URL: ${env:PROD_DB_URL}
    API_DOMAIN: api.test.rokt.dev
